version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_EXTRACTION=${OPENAI_MODEL_EXTRACTION:-gpt-4o-mini}
      - OPENAI_MODEL_AUDIT=${OPENAI_MODEL_AUDIT:-gpt-4o-mini}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
    restart: unless-stopped